Repository informalsystems/quint, pull requests merged in 2023-01, with the labels that each got.

#481 update the makefile and CONTRIBUTING.md
  CONTRIBUTING.md
  Makefile
Labels: devops

#495 Experimental tutorial on integers
  CHANGELOG.md
  Makefile
  README.md
  tutorials/.gitattributes
  tutorials/.tours/integers.tour
  tutorials/Makefile
  tutorials/README.md
  tutorials/lesson2-integers/integers.md
  tutorials/lesson2-integers/integers.qnt
  tutorials/lesson2-integers/integers.template.qnt
  tutorials/script/mk-tutorial.py
  vscode/quint-vscode/server/package.json
Labels: doc

#491 Cleanup and tests for the VSCode extension
  .github/workflows/main.yml
  quint/src/cliCommands.ts
  quint/src/effects/modeChecker.ts
  quint/src/index.ts
  quint/test/effects/modeChecker.test.ts
  vscode/quint-vscode/client/src/extension.ts
  vscode/quint-vscode/package.json
  vscode/quint-vscode/server/package.json
  vscode/quint-vscode/server/src/inferredData.ts
  vscode/quint-vscode/server/src/reporting.ts
  vscode/quint-vscode/server/src/server.ts
  vscode/quint-vscode/server/test/inferredData.test.ts
  vscode/quint-vscode/server/test/reporting.test.ts
  vscode/quint-vscode/server/tsconfig.json
Labels: Fvscode, refactoring

#546 Go to Definition functionality to VSCode
  quint/src/index.ts
  vscode/quint-vscode/CHANGELOG.md
  vscode/quint-vscode/server/package.json
  vscode/quint-vscode/server/src/reporting.ts
  vscode/quint-vscode/server/src/server.ts
  vscode/quint-vscode/server/test/reporting.test.ts
Labels: Fvscode

#554 Regenerate docs and add that to PR checklist
  .github/pull_request_template.md
  doc/builtin.md
Labels: doc

#557 add a few productivity hacks to repl
  CHANGELOG.md
  examples/counters.qnt
  quint/cli-tests.md
  quint/io-cli-tests.md
  quint/src/cli.ts
  quint/src/cliCommands.ts
  quint/src/repl.ts
  quint/test/repl.test.ts
Labels: Fsimulator (phase 5a)

#568 Troubleshooting VSCode instructions
  CONTRIBUTING.md
Labels: doc

#573 add the work-in-progress example after Solidity's SimpleAuction
  CHANGELOG.md
  examples/solidity/SimpleAuction/SimpleAuctionNonComposable.qnt
  quint/cli-tests.md
Labels: example

#576 add the coin example
  CHANGELOG.md
  examples/solidity/Coin/Coin.qnt
  quint/cli-tests.md
Labels: example
